# Generated by Django 5.2.13 on 2026-04-29 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("author", models.CharField(blank=True, db_index=True, max_length=255)),
                ("isbn", models.CharField(blank=True, db_index=True, max_length=32)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("language", models.CharField(blank=True, max_length=50)),
                ("publisher", models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("website", models.URLField()),
                ("logo", models.URLField(blank=True)),
                ("active_status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_url", models.URLField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("limited", "Limited"),
                        ],
                        default="in_stock",
                        max_length=20,
                    ),
                ),
                ("discount_text", models.CharField(blank=True, max_length=100)),
                ("delivery_info", models.CharField(blank=True, max_length=150)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="main.book",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="main.store",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("book", "store"), name="unique_book_store_listing"
                    )
                ],
            },
        ),
    ]
